# Generated by Django 2.2.6 on 2022-05-31 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0003_boxes'),
        ('produtos', '0003_auto_20220531_0750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Boxe',
        ),
    ]
