# Generated by Django 2.2.6 on 2022-06-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0004_delete_boxe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxes',
            name='nome_responsavel',
            field=models.CharField(max_length=60),
        ),
    ]
