# Generated by Django 2.2.6 on 2022-05-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20220531_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('foto_eventos', models.ImageField(blank=True, upload_to='fotos_eventos/%d/%m/%Y')),
            ],
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
