# Generated by Django 2.2.6 on 2022-05-31 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data', models.DateField(blank=True, default=datetime.datetime.now)),
                ('foto_blog', models.ImageField(blank=True, upload_to='fotos_blog/%d/%m/%Y')),
                ('titulo', models.CharField(default='Title', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
