# Generated by Django 2.2.6 on 2022-05-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('foto_receita', models.ImageField(blank=True, upload_to='fotos_contatos/%d/%m/%Y')),
            ],
        ),
    ]
