# Generated by Django 2.2.6 on 2022-05-31 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contatos',
            new_name='Contato',
        ),
    ]
