# Generated by Django 2.2.6 on 2022-06-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0004_remove_contatos_foto_receita'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatos',
            name='contato',
            field=models.TextField(default=''),
        ),
    ]
